{% set name = "youtube-search-python" %}
{% set version = "1.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/youtube-search-python-{{ version }}.tar.gz
  sha256: c7afe70e1ac8e871341d7fb15f5246aac35fd80fec10d7a96d46df2aad608bd0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - httpx >=0.14.2
    - python >=3.6

test:
  imports:
    - youtubesearchpython
    - youtubesearchpython.__future__
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alexmercerind/youtube-search-python
  summary: Search for YouTube videos, channels & playlists & get video information using link WITHOUT YouTube Data API v3
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HeavyTony2
